Player.create(name: "Jeff Bezos", wins:5, losses:2, draws:0)
Player.create(name: "Bill Gates", wins:1, losses:8, draws:3)
Player.create(name: "Justin Trudeau", wins:42, losses:12, draws:10)
Player.create(name: "Stephen Harper", wins:25, losses:22, draws:10)
Player.create(name: "Elon Musk", wins:11, losses:3, draws:9)
